Diffusion Gradient Vector Rotation
==================

William A. Romero R.

In [4]:
import numpy as np

## Image Data

In [17]:
#_______PIXEL_SPACING_(0028,0030)_______
pixelSpacing_cols = 1.40625
pixelSpacing_row  = 1.40625

#_______SPACING_SLICES_(0018,0088)_______
spacingSlices = 1.0

#_______IMAGE_ORIENTATION_PATIENT_(0020,0037)_______
row_x = 0.41218110932147
row_y = 0.85259222512755
row_z = -0.321237032066
col_x = -0.6147261665113
col_y = 6.829280243e-006
col_z = -0.7887406038488

## Diffusion Gradient Vectors (0019,100e)

In [12]:
dgv_1 = [-0.70710677,           0,  0.70710677]
dgv_2 = [-0.70710677,           0, -0.70710677]
dgv_3 = [          0, -0.70710677, -0.70710677]
dgv_4 = [          0, -0.70710677,  0.70710677]
dgv_5 = [ 0.70710677, -0.70710677,           0]
dgv_6 = [-0.70710677, -0.70710677,           0]

## Image Direction

In [24]:
direction = np.zeros( shape=(1,9) )

direction[0,0] = row_x
direction[0,1] = row_y
direction[0,2] = row_z
direction[0,3] = col_x
direction[0,4] = col_y
direction[0,5] = col_z
direction[0,6] = (row_y*col_z) - (row_z*col_y) 
direction[0,7] = (row_z*col_x) - (row_x*col_z) 
direction[0,8] = (row_x*col_y) - (row_y*col_x)

directionMatrixForm =  direction.reshape(3,3)
inverseDirectionMatrix = np.linalg.inv(directionMatrixForm)

print "Image direction: "
print directionMatrixForm

Image direction: 
[[  4.12181109e-01   8.52592225e-01  -3.21237032e-01]
 [ -6.14726167e-01   6.82928024e-06  -7.88740604e-01]
 [ -6.72471913e-01   5.22576786e-01   5.24113565e-01]]


## Rotation

There are two rotation methods related to the image direction in <a href"https://github.com/InsightSoftwareConsortium/ITK">ITK</a> (<a href="https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Core/Common/include/itkImageBase.h">itkImageBase.h</a>)


Method: <strong>TransformLocalVectorToPhysicalVector</strong>
<p style="text-align:justify;color:#3B3B3B;">"Take a vector or covariant vector that has been computed in the
 coordinate system parallel to the image grid and rotate it by the
 direction cosines in order to get it in terms of the coordinate system of
 the image acquisition device.  This implementation in the Image
 multiply the array (vector or covariant vector) by the matrix of Direction
 Cosines."</p>
 
 <p style="text-align:justify;color:#3B3B3B;">The matrix (based on the image direction) that rotates a given vector $\vec{v}$ by a counterclockwise is:</p>

$$R = 
  \begin{pmatrix} 4.12181109e-01 & 8.52592225e-01 & -3.21237032e-01 \\ 
                 -6.14726167e-01 & 6.82928024e-06 & -7.88740604e-01 \\ 
                 -6.72471913e-01 & 5.22576786e-01 & 5.24113565e-01 \end{pmatrix} $$

<p style="text-align:justify;color:#3B3B3B;">Therefore, the rotated vector is given by $R \cdot \vec{v}$</p>

$$v^{'} = 
  \begin{pmatrix} 4.12181109e-01 & 8.52592225e-01 & -3.21237032e-01 \\ 
                 -6.14726167e-01 & 6.82928024e-06 & -7.88740604e-01 \\ 
                 -6.72471913e-01 & 5.22576786e-01 & 5.24113565e-01 \end{pmatrix} 
  \begin{pmatrix} v_x \\ v_y \\ v_z \end{pmatrix} $$

In [34]:
print "Diffusion Gradient Vectors (Rotated: Local Vector To Physical Vector)"
print directionMatrixForm.dot( dgv_1 )
print directionMatrixForm.dot( dgv_2 )
print directionMatrixForm.dot( dgv_3 )
print directionMatrixForm.dot( dgv_4 )
print directionMatrixForm.dot( dgv_5 )
print directionMatrixForm.dot( dgv_6 )

Diffusion Gradient Vectors (Rotated: Local Vector To Physical Vector)
[-0.51860493 -0.12304679  0.84611369]
[-0.06430717  0.99240085  0.10490519]
[-0.37572485  0.55771899 -0.74012183]
[-0.83002261 -0.55772865  0.00108667]
[-0.31141768 -0.43468186 -0.84502703]
[-0.89432979  0.43467221  0.10599186]


Method: <strong>TransformPhysicalVectorToLocalVector</strong>
<p style="text-align:justify;color:#3B3B3B;">"Take a vector or covariant vector that has been computed in terms of the
 coordinate system of the image acquisition device, and rotate it by the
 inverse direction cosines in order to get it in the coordinate system
 parallel to the image grid. This implementation in the Image
 multiply the array (vector or covariant vector) by the inverse of Direction
 Cosines. The arguments of the method are of type FixedArray to make
 possible to use this method with both Vector and CovariantVector."</p>
 
<p style="text-align:justify;color:#3B3B3B;">The rotated vector is given by $R^{-1} \cdot \vec{v}$</p>

$$v^{'} = 
  \begin{pmatrix} 4.12181109e-01 & -6.14726167e-01 & -6.72471913e-01 \\ 
                  8.52592225e-01 &  6.82928024e-06 &  5.22576786e-01 \\ 
                 -3.21237032e-01 & -7.88740604e-01 &  5.24113565e-01 \end{pmatrix} 
  \begin{pmatrix} v_x \\ v_y \\ v_z \end{pmatrix} $$

In [35]:
print "Diffusion Gradient Vectors (Rotated: Physical Vector To Local Vector)"
print inverseDirectionMatrix.dot( dgv_1 )
print inverseDirectionMatrix.dot( dgv_2 )
print inverseDirectionMatrix.dot( dgv_3 )
print inverseDirectionMatrix.dot( dgv_4 )
print inverseDirectionMatrix.dot( dgv_5 )
print inverseDirectionMatrix.dot( dgv_6 )

Diffusion Gradient Vectors (Rotated: Physical Vector To Local Vector)
[-0.76696549 -0.23335615  0.59775313]
[ 0.18405339 -0.97239132 -0.14345537]
[ 0.91018648 -0.36952241  0.18711957]
[-0.04083241  0.36951275  0.92832807]
[ 0.72613309  0.60286891  0.33057494]
[ 0.14322098 -0.60287856  0.7848727 ]
